server {
    listen 3200;
    root /usr/share/nginx/html;
    index index.html;

    # Prevent Cloudflare/browser caching of JS/CSS during development
    location ~* \.(js|css)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
